### PR TITLE
Healthcheck Endpoints

### PR DESCRIPTION
**Pull request by dkoeni**
add healthcheck: /health/ping, /health/live and /health/check

### CODE REVIEW

**Comment by simonmeyerm** [comment]
Our developers reviewed the proposal for the new healthchecks and would suggest to rework it. The 3 healthchecks should differ significantly and offer the possibility to research, why a service is down or restricted. 
Following example would demonstrate the usage of the healthchecks:
_Fintech A wants to make various queries about Bank B accounts. The healthcheck ping endpoint communicates that the system is "UP". Nevertheless, a fault in the service is noticed, which is why Fintech A calls Bank B's Diagnostic endpoint. 
The Diagnostic endpoint confirms that the corresponding API module is currently in an "unhealthy" state and the system is partially down. Furthermore, the current load on this system appears to be at 50%. 

Based on these parameters, Fintech A decides to make certain queries at a later time or has already automated their system to the extent that it distributes or delays the queries based on such parameters. 
If this is not the case, these parameters would be good indicators. In addition, in the event of a failure of individual downstream systems on the consumer side, corresponding messages can be switched proactively._

**Recommended adjustments:**
- /ping: A ping should not be complicated and indicate only the status of the service. Therefore only a message with OK/NOK or UP/DOWN should be returned
- /live: Should be a bit more "complicated" and verify if a request could be processed. Our proposal would be to change the method to POST and process a simple string
- /check: Instead of check, enhance it to diagnostic and return a status like 'Healthy' | 'Unhealthy' | 'Degraded' and message with some information about the issue like 'Operational' | 'Degraded Performance' | 'Partial Outage' | 'Major Outage' | 'Maintenance'. 

It could be a mix between the attached examples:

[short-diagnostic.txt](https://github.com/swissfintechinnovations/ca-payment/files/10765640/short-diagnostic.txt)

[Extended-Diagnostic.txt](https://github.com/swissfintechinnovations/ca-payment/files/10765649/Extended-Diagnostic.txt)

https://docs.tibco.com/pub/amx-bpm/4.3.0/doc/html/bpmhelp/GUID-2BC7A97E-3F13-4E5E-88FD-D9F1073D618F.html

**Review by rolfwagner — APPROVED** [review]
ok - no comments

**Comment by simonmeyerm** [comment]
We discussed your proposal internally and would like to share some of our thoughts and suggestions. The following list explains our interpretation for the use of each endpoint in the proposal.

**/ping:**
Ping is intended for frequent usage and should return OK/NOK based on the simplest possible criteria. This could either be accomplished with the return of the status codes as defined, 200 or 5xx errors. A corresponding schema would only be required for the error cases, which must comply to the general structure of the CommonErrorResponse as defined in the specification.

**/live:**
Live healthcheck should ideally mirror all information from the request back to the requester to allow for validation of sufficient transparency of all nodes throughout the traffic route. This would comply to the current healthcheck design on bLink. 
The mirroring includes:

- the submitted Method
- Headers with values
- payload and DateTime of the request.

In contrast, the live healthcheck currently proposed by SFTI has no defined schema and the example value does not clearly state the purpose of the endpoint.

Further suggestions:
Live healthcheck should ideally allow to check all possible methods of requests that can be submitted in the API. Therefore, for AIS only a GET would be required, PSS GET and POST, for the OpenWealth APIs in addition UPDATE and DELETE.
The Authorization and X-CorAPI-Client-ID Header should be optional, but X-CorAPI-Target-ID required.

**/check**
Given the track record of the current participants on bLink, the functionality as suggested for “check” is highly unlikely to be implemented by the providers. Maybe we didn’t understand the exact purpose here, however, participants are usually not willing to disclose exact information about components or errors and the endpoint is difficult to implement due to the complex infrastructure.
However, the endpoint should be listed for completeness and to follow the general purpose of the healthchecks, but may be a bit simplified with a defined schema, where at least the affected application can be reflected or a logID can be provided in an additional information field.
Still, if the check endpoint is simplified to improve chances of proper implementation, one could ask why the “live” endpoint is not sufficient.

Further suggestions:
Terminology of the endpoints should ideally be more self-explanatory, therefore we suggest something like this:

- Ping -> Ping
- Live -> ConnectivityDiagnostics
- Check -> Diagnostics

We would be glad, if at least /ping and /live could be adjusted according to our feedback.

**Comment by svenbiellmann** [comment]
It was decided that the cross-API topics as health checks will be addressed in a separated stream which will take care of implementing overarching functionalities. Therefore the pull request will be withdrawn and the issue “closed as not planned”.

**Pull request closed without merging**
